### ISSUE TITLE
How to contribute to this project?

### ISSUE THREAD

**Issue by opensourcegeek** [WireGuard/wireguard-rs#1]
Do you have any guidelines on how to contribute to this project? Do you accept PRs here?

**Comment by saschagrunert** [comment]
Hey. Actually not, but I guess this should be an discussion point. I personally would prefer working here as a main repository and mirroring back to the other one. But we have to decide this with the project owner. :)

**Comment by netvl** [comment]
Yep, I support doing the main work here. I think it would be of much benefit to the project.

**Comment by opensourcegeek** [comment]
@saschagrunert I agree, can we check with project owner? I've only read the project's technical whitepaper, I haven't looked into code. Assuming project owner is happy to host project here, even a simple write up on how you're planning to structure this project would be a good starting point to take it further in my opinion.

**Comment by benleb** [comment]
Very good :) What do you think @zx2c4?

**Comment by zx2c4** [comment]
All WireGuard work should have as a canonical location a repository on git.zx2c4.com. This way we keep all repos together. But, because some people like to use github, these repositories are *mirrored* in real time to Github. This is a very common pattern for projects.

So, the actual definitive repository is [git.zx2c4.com/wireguard-rs](https://git.zx2c4.com/wireguard-rs/).

As far as PRs and Issues and various development/maintainer things go, the repository maintainers (essentially Sascha) should use whatever tools they like best. As a kernel developer, personally I very much prefer mailing list style patch postings and discussions, and so I generally do not accept PRs or Issues, and instead shuffle contributors toward [the mailing list](https://lists.zx2c4.com/mailman/listinfo/wireguard). However, Sascha might prefer interacting with contributors via PRs and Issues, or perhaps various other means. And that's perfectly fine. I suspect for Rust development, these modes of interaction will prove more dynamic. So use whatever tools you'd like for this. And if I can make this easier by running any additional infrastructure you might need, I'm at your disposal. The only thing is to always push commits up to git.zx2c4.com. IOW, after you press "merge pull request", the maintainer can type `git pull github master && git push origin master`. (If this extra step becomes burdensome, we can setup automatic 2-way mirroring pretty easily.)
